### ISSUE TITLE
Spark Driver 3.13.1 build number? 

### ISSUE THREAD

**Issue by tommywally** [qnblackcat/How-to-Downgrade-apps-on-AppStore-with-iTunes-and-Charles-Proxy#10]
Please help me find the version before the latest on Spark Driver 3.13.1. I’m trying to downgrade from 3.14.0 and I spent hours trying but can’t. PLEASE!

**Comment by qnblackcat** [comment]
The app is not available in my region. r/jailbreak will be the proper place for this question
