### ISSUE TITLE
Help : I can't find a build version app

### ISSUE THREAD

**Issue by Wretch23** [qnblackcat/How-to-Downgrade-apps-on-AppStore-with-iTunes-and-Charles-Proxy#11]
Hello
I'm following your toturial here : https://github.com/qnblackcat/How-to-Downgrade-apps-on-AppStore-with-iTunes-and-Charles-Proxy/
All was fine untill I had to find the build version...
I checked in the parameters app, on storage information... no build.
![IMG_00771](https://user-images.githubusercontent.com/119760294/205460987-3790671d-3e62-496b-8318-51a3c9632d2c.png)
![IMG_00781](https://user-images.githubusercontent.com/119760294/205460994-a1859387-6749-4d9b-a85d-ef2517f8f00c.png)

I see in your faq you can help é_è, I have nobody with jailbreak :(

I'm trying to downground Mycloud App because they released an update that made it unusable after 4.4.25 version and I did the mistake to update it on my phone... 
It still runs on my ipad I didn't update since.
https://apps.apple.com/us/app/my-passport-wireless/id450655672

The last version available on app store is 4.4.32 and the build one in Charles proxy is
<string>4310509C.BAA3885F.67C82A1A.B2B79FA0.6615B413.0B48FE2A.1334661E</string>
![image](https://user-images.githubusercontent.com/119760294/205461197-525e190b-2766-481d-87d3-90026933673d.png)

I definitly can't deduce which one would be 4.4.25...

Is there any chance you can help me ?

**Comment by qnblackcat** [comment]
> Hello I'm following your toturial here : https://github.com/qnblackcat/How-to-Downgrade-apps-on-AppStore-with-iTunes-and-Charles-Proxy/ All was fine untill I had to find the build version... I checked in the parameters app, on storage information... no build. 

Check https://github.com/qnblackcat/How-to-Downgrade-apps-on-AppStore-with-iTunes-and-Charles-Proxy/#step-1-preparing on how to get the build version number

**Comment by Wretch23** [comment]
Thanks, I missed that part ^^ '
So the build I want is 834210497
![image](https://user-images.githubusercontent.com/119760294/205483378-065b4710-9061-4701-8636-af056baa9ca5.png)

But after I edited in Charles proxy, itune tries to download the app and never ends... :(
![image](https://user-images.githubusercontent.com/119760294/205484044-e512dc77-338d-4432-bd3a-831d6440a7d2.png)

Is there something else I missed ? :(

**Comment by qnblackcat** [comment]
You may need to Excute twice
