### ISSUE TITLE
'This item is being modified. Please try again later.'

### ISSUE THREAD

**Issue by Dr-Sauce** [qnblackcat/How-to-Downgrade-apps-on-AppStore-with-iTunes-and-Charles-Proxy#12]
Did Apple block downgrading apps? I'm suddenly getting this error today.
<img width="960" alt="0025" src="https://user-images.githubusercontent.com/82555878/205490492-5ed938e1-c679-47cb-8e3d-ccc6863d79bb.png">

**Comment by Dr-Sauce** [comment]
I've tried a few other apps and I get the same error. Charles 4.6.3 didn't work so I also tried Charles 4.6.2 (Charles 4.6.3 is the latest version; Charles 4.6.2 used to worked before.) but I'm still getting errors.
![image](https://user-images.githubusercontent.com/82555878/205491407-a590c9bc-8a6f-4042-be42-3fab99383d11.png)

**Comment by qnblackcat** [comment]
I just tried to downgrade an app myself and everything works fine. Does the issue still occur?

**Comment by Dr-Sauce** [comment]
No. I think it's okay now.

Do you know how to solve Charles left panel appearing as blank? It's not happening to me but I've seen some people reporting it.
