### ISSUE TITLE
could not connect to iPhone

### ISSUE THREAD

**Issue by MutayyibAli** [qnblackcat/How-to-Downgrade-apps-on-AppStore-with-iTunes-and-Charles-Proxy#13]
![Screenshot_20221224_024036](https://user-images.githubusercontent.com/16671369/209430258-c3e4100d-b953-40f0-b71c-4c79db6aed7f.png)

**Comment by MutayyibAli** [comment]
When I connect my iPhone I trust from the phone and then is error appears. Can anyone help? I have iPhone 13 Pro Max IOS 16.1.2

**Comment by qnblackcat** [comment]
Why did you plug your phone into your pc tho?

**Comment by MutayyibAli** [comment]
I have Altstore also. And after installing this version of itunes alt store in unable to refresh. Is there a way to make altstore work also? Thanks for tour help!
