### ISSUE TITLE
Build Number for "Jazz Cash" app

### ISSUE THREAD

**Issue by MutayyibAli** [qnblackcat/How-to-Downgrade-apps-on-AppStore-with-iTunes-and-Charles-Proxy#14]
Could you please provide me with the build numbers for the "Jazz Cash" app from v5.0.0 to version 5.1.0? The website only shows build numbers up to version 4.7, which are not working.

There has been an update to the app that is causing me to be unable to login without a SIM card in the phone. Thank you in advance for your assistance.

![Screenshot_20221224_050921](https://user-images.githubusercontent.com/16671369/209436237-1598c2d3-472f-411a-abe8-8cd22e499158.png)

**Comment by MutayyibAli** [comment]
Can anyone help please

**Comment by qnblackcat** [comment]
![Uploading E3B0D9B4-476F-4E5F-9C4B-3300B71ADC36.png…]()

**Comment by qnblackcat** [comment]
![73A5CCF0-24C0-440E-B219-A22B460A0F75](https://user-images.githubusercontent.com/52943116/209461197-be1b9706-0582-4e3b-80f6-dfb573aa712f.png)
