### ISSUE TITLE
There was an error connecting to the Apple ID server

### ISSUE THREAD

**Issue by mig8447** [qnblackcat/How-to-Downgrade-apps-on-AppStore-with-iTunes-and-Charles-Proxy#18]
Hello,

I attempted this on 2 windows computers without success, it seems that the version of iTunes in this tutorial is not able to connect to the Apple ID server any more. Would you have any workaround in mind for this?

I found https://support.apple.com/en-us/HT208104 which makes me think this guide won't work anymore :(

**Comment by qnblackcat** [comment]
I just tested it myself, works fine.

Try open Charles **AFTER** login iTunes

**Comment by Wikinger8** [comment]
It also happened to me because in my SSL proxies I just put an * and not the buyProduct thing
