### ISSUE TITLE
clapper 7.1.0 version id

### ISSUE THREAD

**Issue by KevinDurantsBurner** [qnblackcat/How-to-Downgrade-apps-on-AppStore-with-iTunes-and-Charles-Proxy#20]
is someone able to provide the version of id for clapper 7.1.0? the website in guide only has 6.0

thanks in advance to anyone that can help

**Comment by gingerbeardman** [comment]
I just kicked of the indexing on this page, will need to check back in a short while.

https://ipaarchive.com/app/usa/1522122685 (click "Release" header twice to sort by most recent first, or enter the version you want in the search box)

**Comment by qnblackcat** [comment]
please include the appstore's url of the app

**Comment by gingerbeardman** [comment]
> is someone able to provide the version of id for clapper 7.1.0? the website in guide only has 6.0
> 
> thanks in advance to anyone that can help

There is no 7.1.0 but

- 844268578 7.0.1 | 2021-09-23 06:31:10
