### ISSUE TITLE
The "Lancely" App build number website is down

### ISSUE THREAD

**Issue by Adamsapplespie** [qnblackcat/How-to-Downgrade-apps-on-AppStore-with-iTunes-and-Charles-Proxy#21]
So this is the website linked to find the build number of a given apps older version,
https://tools.lancely.tech/apple/app-search?country=us&query=Notability

I get the following error on their website,
_Sorry, a server error occurred while processing the request:
Failed to get application list_

Any other alternatives out there?

**Comment by gingerbeardman** [comment]
https://ipaarchive.com/app/usa/360593530 (click "Release" header twice to sort by most recent first)

**Comment by qnblackcat** [comment]
Thanks @gingerbeardman. I’ll add this site to the guide
