### ISSUE TITLE
Two issues

### ISSUE THREAD

**Issue by datario-viz** [qnblackcat/How-to-Downgrade-apps-on-AppStore-with-iTunes-and-Charles-Proxy#25]
Two issues arose when I am trying to keep an old version of Apollo

1. At step 3.3 when downloading the application, I forgot to delete the download, and once it conpleted, I cannot access the download tab anymore, and I can’t find a way to delete the file. Anyway to fix?
2. Regarding Charles proxy: when doing the step 3 nothing was recorded in the session tab. Where did I go wrong?

thanks

**Comment by gingerbeardman** [comment]
1. You can delete from the Library section.
2. Start again from the beginning
