### ISSUE TITLE
HELP ME

### ISSUE THREAD

**Issue by kendoughx-cmd** [qnblackcat/How-to-Downgrade-apps-on-AppStore-with-iTunes-and-Charles-Proxy#33]
I did my all but not working...
![s1](https://github.com/qnblackcat/How-to-Downgrade-apps-on-AppStore-with-iTunes-and-Charles-Proxy/assets/90596803/c2e44043-dd36-43f8-a7a8-c53d8c8bacc9)
![s2](https://github.com/qnblackcat/How-to-Downgrade-apps-on-AppStore-with-iTunes-and-Charles-Proxy/assets/90596803/ea43b125-79ac-4237-b6dc-eab3649fa77a)

**Comment by qnblackcat** [comment]
What exactly is your problem?
