### ISSUE TITLE
Is there any way to make this work on Mac?

### ISSUE THREAD

**Issue by up2938** [qnblackcat/How-to-Downgrade-apps-on-AppStore-with-iTunes-and-Charles-Proxy#35]
The instructions say even if I manage to get iTunes on my mac, it won't work. What if I use a Windows emulator, like Parallels? Then will it work?

**Comment by qnblackcat** [comment]
Yes. It *should work

**Comment by slimgym** [comment]
Yes confirmed it does work with parallels using Mac M1 and Win 11 arm.

**Comment by fffelix-jan** [comment]
You will need to use a Windows on Arm virtual machine in Parallels Desktop, which supports x86 emulation.
