### ISSUE TITLE
iTunes won't download the app

### ISSUE THREAD

**Issue by 8biome** [qnblackcat/How-to-Downgrade-apps-on-AppStore-with-iTunes-and-Charles-Proxy#37]
I've made sure to follow the steps correctly, but no matter what I do, it gets stuck. I got the build number for version 203 of Discord (from Reddit because ipa archive only has up to 191; I also tried that one before 203 and it still didn't work). For the record, I haven't done anything like this before so I don't really know what I'm doing even while following the steps, so I don't know where to begin with troubleshooting.

![4034b821b8e8f3fdae474a9e69eba2b5-1](https://github.com/qnblackcat/How-to-Downgrade-apps-on-AppStore-with-iTunes-and-Charles-Proxy/assets/130105383/499840d3-4122-4c04-9ff1-c40b4b749b22)
As you can see at the top, it just gets stuck and doesn't go any further. I've tried probably about 10 times at this point, closing both iTunes and Charles Proxy, and nothing. Any ideas on what I did wrong?

**Comment by SavageKuza** [comment]
Having the same problem, is yours still not working?

**Comment by Joshbloam** [comment]
I get the same thing. It just HANGS at downloading in iTunes. On my fifth attempt.

**Comment by BigtornG** [comment]
when I got to step 4, the download didn't start on iTunes, and a new buyproduct is made on new Charles instead.

![doesn't work](https://github.com/qnblackcat/How-to-Downgrade-apps-on-AppStore-with-iTunes-and-Charles-Proxy/assets/137468297/8d0dbfbc-a67a-4717-89fc-5a62b0914308)
