### ISSUE TITLE
Alternative Websites for Gathering a Build Version Number

### ISSUE THREAD

**Issue by iamdich** [qnblackcat/How-to-Downgrade-apps-on-AppStore-with-iTunes-and-Charles-Proxy#38]
Please provide additional websites for _Method 1_ for _Build version gathering_ (_III. Getting Started >Step 1. Preparing > Build version number gathering_).

Unfortunately Tool Lantency website didn't work for me straight away, it seems their SSL certificate expired (Firefox gives me SSL_ERROR_INTERNAL_ERROR_ALERT) and I can't find a way to force my browser to ignore this error.

The IPA Archive **partially** worked. I really liked that it has release dates next to the build version numbers — it makes a lot easier to guess which app build will work on a particular iOS version. Most other sites I found do not have this. **The problem with IPA Archive** is that for a lot of the apps it says "_indexing app, check back in a few minutes_". I reloaded the page a day after — the error didn't go away. It also throws error 500 and other server errors to me occasionally.

As I don't have access to anyone owning a jailbroken device, _Method 2_ isn't viable for me. And as I need a big list of apps to be installed, brute forcing through all the app build number for each app isn't a great option either.

Thank you for an amazing guide! It saved my mom's iPhone 6 from trash!

**Comment by swindlesmccoop** [comment]
iPA Archive worked for me so give it another try

**Comment by qnblackcat** [comment]
Unfotunately, it's hard to find an alternative to Tool Lantency nowadays.

If you can not find the Build version number of any apps, just file a new issue on this repo. I'll do my best

**Comment by iamdich** [comment]
Thank you everyone. I've solved the issue in a different way, will try to explain (it yet it may be a bit inaccurate, since I was doing it half a year ago, I didn't document all the steps back then, and don't have the device on hand now to retest).

My goal was **to install the latest supported version of an app to a long deprecated version of iOS** (on an iPhone 6).

1. I installed iTunes 12.6.5 for Windows, searched for apps I wanted, downloaded them **to computer** and attempted installing them on the phone (just the latest versions, no need for Charles proxy, etc.).
2. Most of the installations failed or resulted in apps that crashed instantly on launch. I deleted those apps on the phone.
3. After that, I went on App Store **on the phone** and searched for the same apps. Now they were available for download, I got promoted that the latest version of the app compatible with my iOS version will be installed.

As far as I understood the logic, App Store on iOS allows for downloading the latest supported version only if you already had this app in the past. So steps 1,2 tricked it into thinking I already had this app and thus allowing me to install the latest supported version.

**Comment by qnblackcat** [comment]
> As far as I understood the logic, App Store on iOS allows for downloading the latest supported version only if you already had this app in the past. So steps 1,2 tricked it into thinking I already had this app and thus allowing me to install the latest supported version.

You're right. If you've purchased the app in the past, Apple can't just block you from using it. So they give you an option to download the latest version of the app that is compatible with your iOS. This is not the goal of this guide tho
