### ISSUE TITLE
thank you very much for this guide!

### ISSUE THREAD

**Issue by pashosh** [qnblackcat/How-to-Downgrade-apps-on-AppStore-with-iTunes-and-Charles-Proxy#4]
i succeeded to install older versions of shazam, google, google podcasts and google photos on my iphone 5s (ios 12.5.4, with NO jailbreak).
i also tried to install twitter but the latest older build is too old for installing.
again thank you very much!
(i came here from your post on reddit :-))

**Comment by qnblackcat** [comment]
>  i also tried to install twitter but the latest older build is too old for installing.

The latest version of Twitter that supports iOS 12 is `8.6.1`

**Comment by pashosh** [comment]
great, i now have twitter installed :-).

**Comment by qnblackcat** [comment]
Glad to hear that!

**Comment by bmwalters** [comment]
Thank you!
