### ISSUE TITLE
Download doesn't start on iTunes

### ISSUE THREAD

**Issue by BigtornG** [qnblackcat/How-to-Downgrade-apps-on-AppStore-with-iTunes-and-Charles-Proxy#40]
I followed all the steps corrected, however, when I got to step 4, the download didn't start on iTunes, and a new buyproduct is made on new Charles instead.

![doesn't work](https://github.com/qnblackcat/How-to-Downgrade-apps-on-AppStore-with-iTunes-and-Charles-Proxy/assets/137468297/142c8354-8ddb-44e6-9c00-02e6918db261)

**Comment by BigtornG** [comment]
yea, I tried repeating the steps. Same thing happens, iTunes doesn't download the older version

**Comment by BigtornG** [comment]
any luck yet?

**Comment by qnblackcat** [comment]
You may have made a mistake in the previous steps. please follow the guide step by step

**Comment by BigtornG** [comment]
in my previous comment, I repeated the steps, and the same issue occurred.
