### ISSUE TITLE
Update the guide to mention the use of a virtual machine on macOS

### ISSUE THREAD

**Issue by fffelix-jan** [qnblackcat/How-to-Downgrade-apps-on-AppStore-with-iTunes-and-Charles-Proxy#43]
The guide should mention that those who only own a macOS device can install a Windows virtual machine to install the old version of iTunes and download the .ipa. In the case of an Apple Silicon Mac, Windows on Arm running inside Parallels Desktop provides x86 emulation.

**Comment by qnblackcat** [comment]
will do
