### ISSUE TITLE
Installing newer version of IPA  - do I need to uninstall the old version?

### ISSUE THREAD

**Issue by eliluong** [qnblackcat/How-to-Downgrade-apps-on-AppStore-with-iTunes-and-Charles-Proxy#45]
Hello, I have an app on an old version that is working and has my current data. I have downloaded a newer version of the app with the technique explained in this guide (but not the latest). I plan to use `AppManager` to install, but do you generally have to uninstall the old app first? Or can it be upgraded like normal? Thank you.

**Comment by qnblackcat** [comment]
You don't need to uninstall the old app. Doing so will delete all your data, which is obviously bad. Just overwrite it with the new one.
