### ISSUE TITLE
How to know ios version compatible

### ISSUE THREAD

**Issue by ahmaddado** [qnblackcat/How-to-Downgrade-apps-on-AppStore-with-iTunes-and-Charles-Proxy#46]
First thanks alot for this guide it helps alot.
so my question is how we can know the  minmium ios version for the older versions of the app?

**Comment by qnblackcat** [comment]
Actually, we don't know until we download the iPA and install (or unzip) it.

Maybe you're looking for this? https://github.com/qnblackcat/How-to-Downgrade-apps-on-AppStore-with-iTunes-and-Charles-Proxy/issues/38#issuecomment-2144382598
