### ISSUE TITLE
Is It Possible To Downgrade Safari?

### ISSUE THREAD

**Issue by Execullaa** [qnblackcat/How-to-Downgrade-apps-on-AppStore-with-iTunes-and-Charles-Proxy#47]
Can't find Safari on App Store and can't remove it on iPad. Is there any way to downgrade it? Thanks!

**Comment by nar001** [comment]
Safari is a system app and not downloaded through the App Store, so you can't. Sorry!

**Comment by qnblackcat** [comment]
nope, literally impossible
