### ISSUE TITLE
Hi, use NB Pro to downgrade apps without charles proxy

### ISSUE THREAD

**Issue by panderman** [qnblackcat/How-to-Downgrade-apps-on-AppStore-with-iTunes-and-Charles-Proxy#48]
Hi, i found an app named NB Pro, it's awesome to downgrade app old versions only with iPhone.

![IMG_1E0DC54136A1-1](https://github.com/qnblackcat/How-to-Downgrade-apps-on-AppStore-with-iTunes-and-Charles-Proxy/assets/2589642/c4e58607-d85c-4fa4-8847-89cf28a40206)

**Comment by YoXpertguyZ** [comment]
can you send a link i cant seen to find this online

**Comment by qnblackcat** [comment]
looks cool but it requires you to sideload it first. Also it's from China...
