### ISSUE TITLE
Build number for discord versions 205-232?

### ISSUE THREAD

**Issue by elitemikaelsonheiressqueen** [qnblackcat/How-to-Downgrade-apps-on-AppStore-with-iTunes-and-Charles-Proxy#50]
Would it please be possible to locate the build numbers for discord version 205 to 232? Here's the link — https://apps.apple.com/us/developer/discord-inc/id658886503

The reason I'm asking for all of these is because I accidentally had it updated and it was too inaccessible for me to access my dms when they changed it to the top of the screen but now I can't remember which version I had prior.

Thank you!

**Comment by qnblackcat** [comment]
This is the iTunesMetadata file of Discord, which contains all the Build version numbers of Discord at the time (03 Nov 2024)

[Discord's iTunesMetadata.txt](https://github.com/user-attachments/files/17609998/iTunesMetadata.txt)
