### ISSUE TITLE
Is there any way to load older iOS/iPadOS apps version on macOS?

### ISSUE THREAD

**Issue by HumanixSaektati** [qnblackcat/How-to-Downgrade-apps-on-AppStore-with-iTunes-and-Charles-Proxy#6]
Have you ever tested Apple Configurator 2 https://apps.apple.com/us/app/apple-configurator-2/id1037126344 on macOS to see if this method works?

Another question, is there also generally a way to get tvOS apps and watchOS apps ipa file?

**Comment by qnblackcat** [comment]
There is no way to do it AFAIK. However, you can setup bootcamp or run a VM Windows machine, then install iTunes 12.6.5 and Charles Proxy

**Comment by HumanixSaektati** [comment]
Hi can confirm that it works on Windows 11 with iTunes 12.6.5 and Charles Proxy v4.6.2.

But how long will this method work, do you think Apple can remove it in general this possibility for iTunes 12.6.5 on Windows?

**Comment by qnblackcat** [comment]
I don't think so. This method has existed for years. But yes, they can remove it at anytime.
