### ISSUE TITLE
iTunes won't open

### ISSUE THREAD

**Issue by kikazu** [qnblackcat/How-to-Downgrade-apps-on-AppStore-with-iTunes-and-Charles-Proxy#7]
When I try to open iTunes 12.6.5, there's an error: "This version of iTunes has not been correctly configured" on Windows 10 Home.

**Comment by qnblackcat** [comment]
strange... I've never seen this issue before. Have you tried to Google this issue?

**Comment by kikazu** [comment]
I never found anything, however I tried on another computer running Windows 10 Pro and it worked, that was a month ago.

Now I’m doing this again on the same computer but after I press “download” in iTunes, the download never starts. It keeps saying “downloading app name” and there’s no actual download so I can’t cancel it.
