### ISSUE TITLE
iTunes won't connect my phone

### ISSUE THREAD

**Issue by Sparktion** [qnblackcat/How-to-Downgrade-apps-on-AppStore-with-iTunes-and-Charles-Proxy#9]
When plugging in iPhone SE 2020, iOS 16.0 beta: 
![image](https://user-images.githubusercontent.com/59346386/195748700-39e34ce7-e49c-45ed-ac08-82d7c5e58f03.png)

**Comment by qnblackcat** [comment]
But why did you connect your phone to your computer tho? To install ipa? If it’s the case, don’t use iTunes, just follow my guide

**Comment by Sparktion** [comment]
Realized later, just assumed. The guide worked, super cool stuff!
